name: publish to Docker Hub

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker:
    name: publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: authenticate
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: handle metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rahilp/csp-builder
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
